// Generated by scripts/build-charts.py --sections-output — do not edit by hand.

import type { SongId } from "@/data/game";

export type SectionType = "intro" | "verse" | "chorus" | "bridge" | "outro";

export type SongSection = {
  type: SectionType;
  /** Milliseconds into the shipped audio file, countdown head included. */
  startMs: number;
  endMs: number;
};

/** Contiguous boundaries inferred from vocal rests and local tile density. */
export const songSections = {
  mrfy: [
    { type: "intro", startMs: 0, endMs: 23963 },
    { type: "verse", startMs: 23963, endMs: 47926 },
    { type: "chorus", startMs: 47926, endMs: 83870 },
    { type: "verse", startMs: 83870, endMs: 119815 },
    { type: "chorus", startMs: 119815, endMs: 183716 },
    { type: "bridge", startMs: 183716, endMs: 197695 },
    { type: "chorus", startMs: 197695, endMs: 215667 },
    { type: "outro", startMs: 215667, endMs: 219384 },
  ],
  kokosy: [
    { type: "intro", startMs: 0, endMs: 25078 },
    { type: "verse", startMs: 25078, endMs: 67709 },
    { type: "chorus", startMs: 67709, endMs: 107833 },
    { type: "verse", startMs: 107833, endMs: 147958 },
    { type: "chorus", startMs: 147958, endMs: 190589 },
    { type: "bridge", startMs: 190589, endMs: 208144 },
    { type: "outro", startMs: 208144, endMs: 229368 },
  ],
  tabu: [
    { type: "intro", startMs: 0, endMs: 24706 },
    { type: "verse", startMs: 24706, endMs: 56471 },
    { type: "chorus", startMs: 56471, endMs: 84706 },
    { type: "verse", startMs: 84706, endMs: 123530 },
    { type: "chorus", startMs: 123530, endMs: 160589 },
    { type: "verse", startMs: 160589, endMs: 192354 },
    { type: "bridge", startMs: 192354, endMs: 201178 },
    { type: "chorus", startMs: 201178, endMs: 235752 },
    { type: "outro", startMs: 235752, endMs: 241752 },
  ],
} satisfies Record<SongId, SongSection[]>;
